name: non-reg-tests_ubuntu-latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    runs-on: ubuntu-latest
    #container: ndesassis/test_ubuntu-16 # If restored, github workflow cannot change to swigex/build directory !!!

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Python dependency
      run: sudo apt-get update && sudo apt-get install -yq python3-numpy
      
    - name: Install R dependencies
      run: sudo apt-get install r-base
      
    - name: Setup personal R libraries directory
      # Beware : ~/ is Linux only. For a potential windows a solution must be found yet
      run: mkdir -p ~/r_libs & echo ".libPaths('~/r_libs')" > ~/.Rprofile

    - name: Configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Compile, install packages and execute non-regression tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check
