name: nonreg-demos-courses_ubuntu16

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on main branch
  #push:
  #  branches: [ main ]
  # Activate the workflow at each pull request on main branch
  #pull_request:
  #  branches: [ main ]
  # Activate the workflow every day at 23:30 UTC = for Paris 00:30 (summer) or 01:30 (winter)
  #schedule:
  #  # * is a special character in YAML so you have to quote the string
  #  - cron:  '30 23 * * *'
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        # Corresponding docker file comes from:
        # https://github.com/fabien-ors/docker-generate
        image: fabienors/ubuntu-16-demos-rmd-ipynb

    steps:
    - uses: actions/checkout@v2

    - name: Install gstlearn
      run: |
        export PATH=/opt/python/py311/bin:$PATH
        python3 -m pip install --upgrade pip
        python3 -m pip install gstlearn

    - name: Compile and execute demos and courses tests
      run: |
        export PATH=/opt/python/py311/bin:$PATH
        alias pip="python3 -m pip"
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_PYTHON=ON -DBUILD_R=ON
        cmake --build ${{env.BUILD_DIR}} --target check_ipynb -- -j 3
        cmake --build ${{env.BUILD_DIR}} --target check_rmd -- -j 3
