name: non-reg-tests_windows-latest-visual

on:
  # Deactivate the workflow
  push:
    branches-ignore:
      - '**'
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build
  PYTHON_VERSION : "3.10"

jobs:
  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
        
    - name: Install Python dependency
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy

    - name: Configure cmake
      run: cmake -B${{env.BUILD_DIR}} -DBUILD_PYTHON=ON

    - name: Compile, install packages and execute non-regression tests
      # Execute tests defined by the CMake configuration.
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target check
