name: non-reg-tests_windows-latest-visual

on:
  # Deactivate the workflow
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python dependency
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy

    - name: Configure cmake
      run: cmake -B${{env.BUILD_DIR}} -DPython_ROOT_DIR="${{ env.pythonLocation }}"

    - name: Compile, install packages and execute non-regression tests
      # Execute tests defined by the CMake configuration.
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target check
