name: nonreg-tests_ubuntu-latest

on:
  # Deactivate the workflow
  #push:
  #  branches-ignore:
  #    - '**'
  # Activate the workflow at each push on main branch
  push:
    branches: [ main ]
  # Activate the workflow at each pull request on main branch
  pull_request:
    branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR : build
  PYTHON_VERSION : "3.11"
  SWIG_ROOT : ${{github.workspace}}/swig_420b

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq r-base

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy

    - name: Setup personal R libraries directory
      run: mkdir -p ~/r_libs & echo ".libPaths('~/r_libs')" > ~/.Rprofile

    - name: Install R dependencies
      run: Rscript -e "install.packages(c('devtools'), repos='https://cloud.r-project.org/', dependencies = TRUE)"

    - name: Compile and install [customized] SWIG 4.2.0
      run: |
        mkdir swig_src
        cd swig_src
        git clone https://github.com/fabien-ors/swig.git
        cd swig
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX:PATH=${{env.SWIG_ROOT}} -DCMAKE_BUILD_TYPE:STRING=Release 
        cd build
        make
        make install

    - name: Configure Cmake
      run: cmake -B ${{github.workspace}}/${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_PYTHON=ON -DBUILD_R=ON -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig

    - name: Compile, install packages and execute non-regression tests
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --target check