name: nonreg-demos-courses_python_ubuntu-latest

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
   # Activate the workflow at each push on main branch
  #push:
  #  branches: [ main ]
  # Activate the workflow at each pull request on main branch
  #pull_request:
  #  branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  PYTHON_VERSION : "3.13"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -yq pandoc

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{env.PYTHON_VERSION}}
        activate-environment: true

    - name: Install Python dependencies
      run: |
        uv pip install --upgrade pip
        uv pip install numpy
        uv pip install jupyter
        uv pip install notebook==6.1.6
        uv pip install matplotlib
        uv pip install plotly
        uv pip install gstlearn

    - name: Configure build directory for python package
      run: |
        cmake \
          -B${{ env.BUILD_DIR }} \
          -DBUILD_PYTHON=ON \

    - name: Build the package
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target python_build

    - name: Execute Python demos and courses
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target check_ipynb

    - name: Compress output logs
      if: success() || failure()
      run: |
        cd ${{env.BUILD_DIR}}/tests
        find . -type f \( -name "*.asciidoc" \) -print0 | tar -czvf demos-courses-python-logs.tar.gz --null -T -

    - name: Publish output logs as artefact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: demos-courses-python-logs
        path: ${{env.BUILD_DIR}}/tests/demos-courses-python-logs.tar.gz
