name: non regression tests under Windows (Visual)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PYTHON3_PREF : C:\\hostedtoolcache\\windows\\Python
  # TODO: to be regularly updated according available pythons on windows-latest
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
  PYTHON3_VERSION : 3.10.6

jobs:
  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name : Create PYTHONPATH
      run : |
        echo ("PYTHONPATH=${{ env.PYTHON3_PREF }}\\${{ env.PYTHON3_VERSION }}\\x64")>> $env:GITHUB_ENV
      
    - name : Setup python.exe 
      run : echo ("PYTHON3=${{env.PYTHONPATH}}\\python3.exe") >> $env:GITHUB_ENV
 
    - name : Modify PATH #to avoid a warning at cmake configuration
      run : |
        echo "${{env.PYTHONPATH}}\\Scripts" >> $GITHUB_PATH

    - name: Install Python dependency
      run: ${{env.PYTHON3}} -m pip install numpy

    - name: Configure cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Compile, install packages and execute non-regression tests
      # Execute tests defined by the CMake configuration.  
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check
