name: publish_python_macos-10-11

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy :
      matrix:
       python: ["3.7","3.8","3.9","3.10"]
       os : [macos-10.15,macos-11]
       include :
       - os :  macos-10.15
         TAG : "macosx_10_15_x86_64"

       - os  : macos-11
         TAG : "macosx_11_0_arm64"

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy twine wheel

    - name : Create Wheels
      run : |
        # Error locating python on MacOS : https://github.com/actions/setup-python/issues/121
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:${{env.BUILD_TYPE}} -DPython3_ROOT_DIR="${{env.pythonLocation}}" -DBUILD_PYTHON=ON
        cmake --build ${{env.BUILD_DIR}} --target python_build
        cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
        # Note: wheel must be declared pure (see setup.py)
        python setup.py bdist_wheel --plat-name=${{matrix.TAG}}

    - name : Upload
      run : python -m twine upload ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TWINE_PYPI_PWD}}
        TWINE_REPOSITORY: pypi
