name: publish_python_ubuntu-latest

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
jobs:
   
  build:
    runs-on: ubuntu-latest
    strategy :
      matrix:
    #   python: ["py35",'py36',"py37","py38","py39","py310"]
       python: ["3.7","3.8","3.9","3.10"]
    #container:
    #  image: ndesassis/test_ubuntu-16
 
    steps:
   
    - uses: actions/checkout@v2
    
    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}

    - name: Install Python dependency
      run: |
        which python
        which python3
        python -m pip install --upgrade pip
        python -m pip install numpy twine wheel
      
    - name : Create Wheels
      run : |
        cmake -Bbuild -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF
        cmake --build build --target python_build
        cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
        # Note: wheel must be declared pure (see setup.py)
        python setup.py bdist_wheel --plat-name=manylinux1_x86_64

    - name : Upload
      run : |
        python -m twine upload ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PYPI_PWD }}
        TWINE_REPOSITORY: pypi

   

