name: publish_python_macos

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'     
        required: false
        default: ''  
env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  PYTHON3 : python3
  PROG_ROOT : '/Users/runner/work/'
 
jobs:   
  build:
    runs-on: macos-11 
    steps:
    - uses: actions/checkout@v2
    
    - name : Install wheel and twine
      run: |
       ${{env.PYTHON3}} -m pip install wheel
       ${{env.PYTHON3}} -m pip install twine
       ${{env.PYTHON3}} -m pip install numpy 

    - name : Configure Cmake
      run : cmake -B${{env.BUILD_DIR}} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBoost_ROOT=${{env.BOOST_ROOT}} -DHDF5_ROOT:PATH=${{env.PROG_ROOT}}/${{env.HDF5_ROOT}}  -DCMAKE_C_FLAGS="-DH5_USE_110_API"  

    - name : Build python package
      run : cmake --build ${{env.BUILD_DIR}} --target python_install --config Release

    - name : Build and upload wheel
      run: |
        cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
        ${{env.PYTHON3}} setup.py bdist_wheel --python-tag=cp39 --plat-name=macosx_10_15_x86_64
        ${{env.PYTHON3}} -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
        TWINE_REPOSITORY: testpypi

#--plat-name=macosx_11
    

   


   

