name: publish_python_macos-latest

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
 
jobs:   
  build:
    runs-on: macos-latest
    strategy :
      matrix:
       python: ["3.7","3.8","3.9","3.10"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy twine wheel

    - name : Create Wheels
      run : |
        # Error locating python on MacOS : https://github.com/actions/setup-python/issues/121
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DPython3_ROOT_DIR="${{ env.pythonLocation }}"
        cmake --build ${{env.BUILD_DIR}} --target python_build
        cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
        # Note: wheel must be declared pure (see setup.py)
        python setup.py bdist_wheel --plat-name=macosx_10_15_x86_64

    - name : Upload
      run : python -m twine upload ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PYPI_PWD }}
        TWINE_REPOSITORY: pypi

#--plat-name=macosx_11
    

   


   

