name: publish_doc

on:
  # Activate the workflow every 15 days at 23:30 UTC = for Paris 00:30 (summer) or 01:30 (winter)
  schedule:
    # * is a special character in YAML so you have to quote the string
    - cron: '30 23 */15 * *'
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: false

env:
  BUILD_DIR : build
  
jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
      project_version: ${{ steps.main_step.outputs.PROJECT_FULL_VERSION }}

    steps:
    - uses: actions/checkout@v4

    - name: Get project version
      id: main_step
      run: |
        cmake -B${{env.BUILD_DIR}} -DBUILD_PYTHON=OFF -DBUILD_R=OFF
        PROJECT_FULL_VERSION=$(cmake --build ${{env.BUILD_DIR}} --target print_version | grep PROJECT_FULL_VERSION | cut -d "=" -f2 | xargs)
        echo "PROJECT_FULL_VERSION=${PROJECT_FULL_VERSION}" >> "$GITHUB_OUTPUT"

  call-doxygen:
    uses: ./.github/workflows/publish_doxygen.yml
    secrets: inherit
  call-demos:
    uses: ./.github/workflows/publish_demos.yml
    secrets: inherit

  call-publish:
    needs: [get-version, call-doxygen, call-demos]
    if: ${{ (inputs.dry_publish == false) && (github.event_name != 'schedule') }}
    
    # Only ubuntu can upload to a server easily (ssh)
    runs-on: ubuntu-latest
    
    steps:
      - env:
          PROJECT_VERSION: ${{needs.get-version.outputs.project_version}}
        uses: fabien-ors/folder-publish-action@v4
        with:
          host: ${{ secrets.CG_HOST }}
          username: ${{ secrets.CG_USR }}
          password: ${{ secrets.CG_PWD }}
          dest-path: "/var/www/html/swigex/${{env.PROJECT_FULL_VERSION}}"
          name: demos

      - env:
          PROJECT_VERSION: ${{needs.get-version.outputs.project_version}}
        uses: fabien-ors/folder-publish-action@v4
        with:
          host: ${{ secrets.CG_HOST }}
          username: ${{ secrets.CG_USR }}
          password: ${{ secrets.CG_PWD }}
          dest-path: "/var/www/html/swigex/${{env.PROJECT_FULL_VERSION}}"
          name: doxygen

