name: test-r-script

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.3.0

    - name : Run a R script
      run : |
        Rscript r/test_r_script.R
